In [1]:
#生成数据
import numpy as np
#生成随机数
np.random.seed(1234)
x = np.random.rand(500,3)
#构建映射关系，模拟真实的数据待预测值,映射关系为y = 4.2 + 5.7*x1 + 10.8*x2，可自行设置值进行尝试
y = x.dot(np.array([4.2,5.7,10.8]))
print(x)
print(y)

[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]
 [0.27646426 0.80187218 0.95813935]
 ...
 [0.77485433 0.17616405 0.88455879]
 [0.09306395 0.20218845 0.37240548]
 [0.17365571 0.34523374 0.56773848]]
[ 9.07786127 10.68836829 16.0797263  11.12922286 10.93165403  5.37329728
 12.21769522  6.99763629 11.92183168 11.25409795 14.79971809 12.22758633
 10.96579249  6.1503401  10.46766117  8.55032711  5.45997705  5.8491499
 16.33001627 18.18512486  9.92349225  3.58288103  8.83293151 11.05386043
  5.06704001 11.94254694  6.45817975 14.56271085 11.87672677 11.83621297
  9.58556266 12.16169141  7.54118908 14.83178201 16.95711344  7.2010966
  9.41633216 13.36307267  8.89049525 13.53761433 16.59743526  5.81093283
  5.94787817  8.45044079  7.09175585  8.17099288  4.67392227 15.3674629
 10.1211939   6.69616873 10.66032044 13.32990072 15.52396023 11.07875215
 19.80253898 11.41929488 15.69679186 12.79052379  9.04353678 15.40296188
 14.50745991  5.85626504 10.82684019  6.46258723  6

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline

# 调用模型
lr = LinearRegression(fit_intercept=True)
# 训练模型
lr.fit(x,y)
print("估计的参数值为：%s" %(lr.coef_))
# 计算R平方
print('R2:%s' %(lr.score(x,y)))
# 任意设定变量，预测目标值
x_test = np.array([2,4,5]).reshape(1,-1)
y_hat = lr.predict(x_test)
print("预测值为: %s" %(y_hat))

估计的参数值为：[ 4.2  5.7 10.8]
R2:1.0
预测值为: [85.2]


In [3]:
#2.牛顿迭代法
class LR_LS():
    def __init__(self):
        self.w = None      
    def fit(self, X, Y):
        # 最小二乘法矩阵求解
        self.w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
    def predict(self, X):
        # 用已经拟合的参数值预测新自变量
        y_pred = X.dot(self.w)
        return y_pred

if __name__ == "__main__":
    lr_ls = LR_LS()
    lr_ls.fit(x,y)
    print("估计的参数值：%s" %(lr_ls.w))
    x_test = np.array([2,4,5]).reshape(1,-1)
    print("预测值为: %s" %(lr_ls.predict(x_test)))

估计的参数值：[ 4.2  5.7 10.8]
预测值为: [85.2]


In [4]:
#3.梯度下降法
class LR_GD():
    def __init__(self):
        self.w = None     
    def fit(self,X,y,alpha=0.02,loss = 1e-10): # 设定步长为0.002,判断是否收敛的条件为1e-10
        y = y.reshape(-1,1) #重塑y值的维度以便矩阵运算
        [m,d] = np.shape(X) #自变量的维度
        self.w = np.zeros((d)) #将参数的初始值定为0
        tol = 1e5
        #============================= show me your code =======================
        while tol > loss:
            h_f = X.dot(self.w).reshape(-1,1) 
            theta = self.w + alpha*np.mean(X*(y - h_f),axis=0) #计算迭代的参数值
            tol = np.sum(np.abs(theta - self.w))
            self.w = theta
        #============================= show me your code =======================
    def predict(self, X):
        # 用已经拟合的参数值预测新自变量
        y_pred = X.dot(self.w)
        return y_pred  

if __name__ == "__main__":
    lr_gd = LR_GD()
    lr_gd.fit(x,y)
    print("估计的参数值为：%s" %(lr_gd.w))
    x_test = np.array([2,4,5]).reshape(1,-1)
    print("预测值为：%s" %(lr_gd.predict(x_test)))

估计的参数值为：[ 4.20000001  5.70000003 10.79999997]
预测值为：[85.19999995]
